---
title: "Homework 4 Part 1"
author: "Angel Garcia de la Garza"
date: "10/24/2017"
output: html_document
---

```{r setup, include=FALSE}

#Load libraries

library(tidyverse)
library(haven)
library(janitor)

```

## Part 1

### This is my collaboration to the project

```{r tidy_data}

## Gather the pups data to long format

pups_data <- read_csv("./FAS_pups.csv") %>% ## Load the data
              clean_names() %>% ## Clean Names
              mutate(id = 1:313) %>% ## Create Pup ID
              gather(key = outcome, 
                     value = post_natal_days, pd_ears:pd_walk) ## Gather to long format
              
```

## Part 2

```{r}

##  Distribution of post-natal days for each developmental landmark

ggplot(pups_data, aes(x = outcome, y = post_natal_days)) + 
  geom_violin(aes(fill = outcome)) +
  labs(title = "Distribution of Post-Natal Days by Outcome",
       x = "Outcome",
       y = "Number of Post-Natal Days")


library(ggridges)

ggplot(pups_data, aes(x = post_natal_days, y = outcome)) + 
  geom_density_ridges(scale = 0.85) +
  labs(title = "Distribution of Post-Natal Days by Outcome",
       x = "Number of Post-Natal Days",
       y = "Outcome")

```

First, we observe that the distribution of post-natal days for each outcome looks very bumpy. Outcome, "pd_ears" ranges from about 2 to 5 post-natal days, "pd_eyes" from about 11 to 15, "pd_pivot" from about 4 to 11 and "pd_walk" from about 7 to 13. It is clear from the plots that the number of post-natal days differs by outcome. 
